#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Create a new OpenSCAD project with multi-part template."""
import argparse
import os
import sys
from pathlib import Path

SCAD_HOME = Path(os.environ.get("SCAD_HOME", "~/.scad")).expanduser()

TEMPLATE = '''// OpenSCAD project: {name}
// Generated by scad_new_project.py

include <BOSL2/std.scad>

$fn = 64;       // Preview quality (raise to 128+ for final render)
$slop = 0.15;   // Printer tolerance (0.1-0.2mm typical for FDM)

PART = "all";   // "a", "b", or "all"

module part_a() {{
    // TODO: implement part A
    cuboid([30, 20, 10], rounding=2);
}}

module part_b() {{
    // TODO: implement part B
    cyl(h=15, r=5, rounding=1);
}}

module assembly() {{
    part_a();
    up(12.5) part_b();
}}

if (PART == "a") {{
    part_a();
}} else if (PART == "b") {{
    part_b();
}} else {{
    assembly();
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a new OpenSCAD project")
    parser.add_argument("name", help="Project name (creates ~/.scad/<name>/main.scad)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing main.scad")
    args = parser.parse_args()

    project_dir = SCAD_HOME / args.name
    project_dir.mkdir(parents=True, exist_ok=True)

    main_scad = project_dir / "main.scad"
    if main_scad.exists() and not args.force:
        print(f"{main_scad} already exists. Use --force to overwrite.")
        return 1

    main_scad.write_text(TEMPLATE.format(name=args.name), encoding="utf-8")
    print(f"Created {main_scad}")
    print(f"\nNext steps:")
    print(f"  1. Edit the design: {main_scad}")
    print(f"  2. Validate: ./scripts/scad_tool.py validate --in {main_scad}")
    print(f"  3. Screenshot: ./scripts/scad_tool.py screenshots --in {main_scad} --preset single")
    print(f"  4. Render STL: ./scripts/scad_tool.py stl --in {main_scad}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
